language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - hhvm

notifications:
  email: false

before_script:
  - cp include/configuration-template.php include/configuration.php

script:
  - phpunit test.php